name: CI/CD Build, Push & Deploy for ecommerce-app

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ "main" ]

env:
  REGISTRY: gcr.io
  PROJECT: devops-492107
  APP: ecommerce-frontend
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      tagname: ${{ steps.tag.outputs.tagname }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate Tag
        id: tag
        run: echo "tagname=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEVOPS_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Image
        run: |
          docker build ./frontend \
          -f frontend/Dockerfile \
          -t $REGISTRY/$PROJECT/$APP:${{ steps.tag.outputs.tagname }}

      - name: Push Image
        run: |
          docker push $REGISTRY/$PROJECT/$APP:${{ steps.tag.outputs.tagname }}

  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout workspace
  #       uses: actions/checkout@v4

  #     - name: Install SSH client
  #       run: sudo apt-get update && sudo apt-get install -y openssh-client

  #     - name: Configure SSH key
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
  #         chmod 600 ~/.ssh/id_rsa

  #     - name: Deploy docker-compose to VM
  #       env:
  #         IMAGE_TAG: ${{ env.IMAGE_TAG }}
  #         ARTIFACT_REGISTRY_URL: ${{ env.ARTIFACT_REGISTRY_URL }}
  #         VM_HOST: ${{ secrets.VM_SSH_HOST }}
  #         VM_USER: ${{ secrets.VM_SSH_USER }}
  #         VM_PORT: ${{ secrets.VM_SSH_PORT }}
  #       run: |
  #         ssh_port="${VM_PORT:-22}"

  #         cat > /tmp/docker-compose.deploy.yml <<EOF
  #         version: "3"
  #         services:
  #           backend:
  #             image: ${ARTIFACT_REGISTRY_URL}/backend:${IMAGE_TAG}
  #             ports:
  #               - "5000:5000"
  #           frontend:
  #             image: ${ARTIFACT_REGISTRY_URL}/frontend:${IMAGE_TAG}
  #             ports:
  #               - "3000:3000"
  #             depends_on:
  #               - backend
  #         EOF

  #         scp -o StrictHostKeyChecking=no -P "${ssh_port}" /tmp/docker-compose.deploy.yml "${VM_USER}@${VM_HOST}:/tmp/docker-compose.deploy.yml"

  #         ssh -o StrictHostKeyChecking=no -p "${ssh_port}" "${VM_USER}@${VM_HOST}" \
  #           'docker-compose -f /tmp/docker-compose.deploy.yml pull && docker-compose -f /tmp/docker-compose.deploy.yml up -d'
